module.exports=[
    {
    name:"Atlanta Hawks",
    formation: 1946,
    championships: 1,
    image: "https://cdn.freebiesupply.com/images/large/2x/atlanta-hawks-logo-transparent.png",
    highlights: "https://www.youtube.com/embed/C9N7kGi2-uE",
    stadium:"State Farm Arena",
    },
    {
    name:"Boston Celtics",
    formation: 1947,
    championships: 17,
    image: "https://cdn.freebiesupply.com/images/large/2x/boston-celtics-logo-transparent.png",
    highlights: "https://www.youtube.com/embed/F5OSosFrUp4",
    stadium:"TD Bank North Garden",
        },
    {
    name:"Brooklyn Nets",
    formation: 1947,
    championships: 0,
    image: "https://basketballjerseyarchive.com/static/logos/3XeZnZxNaCR2SYc/brooklyn-nets-1990-1997-logo.png",
    highlights: "https://www.youtube.com/embed/qXtA21G26Dc",
    stadium:"Barclay's Center",
    },
    {
    name:"Charlotte Hornets",
    formation: 1988,
    championships: 0,
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/Charlotte_Hornets_%282014%29.svg/800px-Charlotte_Hornets_%282014%29.svg.png",
    highlights: "https://www.youtube.com/embed/1-4Hx1Uzk2M",
    stadium:"Spectrum Arena",
    },
    {
    name:"Chicago Bulls",
    formation: 1966,
    championships: 6,
    image: "https://cdn.freebiesupply.com/images/large/2x/chicago-bulls-logo-transparent.png",
    highlights: "https://www.youtube.com/embed/j1l-vxbQbZA",
    stadium:"United Center",
    },
    {
    name:"Cleveland Cavaliers",
    formation: 1966,
    championships: 1,
    image: "https://1000logos.net/wp-content/uploads/2017/08/CAVS-Logo-2010.png",
    highlights: "https://www.youtube.com/embed/d2nii8bCFZs",
    stadium:"Rocket Mortgage Fieldhouse",
    },
    {
    name:"Dallas Mavericks",
    formation: 1980,
    championships: 1,
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/9/97/Dallas_Mavericks_logo.svg/640px-Dallas_Mavericks_logo.svg.png",
    highlights: "https://www.youtube.com/embed/pmxBewqSEUs",
    stadium:"American Airlines Center",
    },
    {
    name:"Denver Nuggets",
    formation: 1967,
    championships: 0,
    image: "https://cdn.freebiesupply.com/images/large/2x/denver-nuggets-logo-transparent.png",
    highlights: "https://www.youtube.com/embed/pmxBewqSEUs",
    stadium:"Pepsi Center",
    },
    {
    name:"Detroit Pistons",
    formation: 1941,
    championships: 3,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Detroit-Pistons-Logo-2005-to-2017.png/1200px-Detroit-Pistons-Logo-2005-to-2017.png",
    highlights: "https://www.youtube.com/embed/rkH56uneMx8",
    stadium:"Little Caesars Arena",
    }, 
    {
    name:"Golden State Warriors",
    formation: 1946,
    championships: 6,
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/0/01/Golden_State_Warriors_logo.svg/1200px-Golden_State_Warriors_logo.svg.png",
    highlights:"https://www.youtube.com/embed/l_mJyIurB_8",
    stadium:"Oracle Arena",
    }, 
    {
        name:"Houston Rockets ",
        formation: 1967,
        championships: 2,
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/2/28/Houston_Rockets.svg/800px-Houston_Rockets.svg.png",
        highlights:"https://www.youtube.com/embed/gJA5jU2cfE8",
        stadium:"Toyota Center",
        },          
]